export const academicData = [
  {
    semester: "高一上学期",
    examName: "10月", // 精简
    class: 9,
    subjects: {
      语文: 108,
      数学: 119,
      英语: 83.5,
      物理: 69,
      化学: undefined,
      生物: undefined,
    },
    originalTotalScore: 442.5,
    originalClassRank: "29",
    originalSchoolRank: "641",
    selectedSubjectsTotalScore: 108 + 119 + 83.5 + 69,
    selectedSubjectsClassRank: null,
    selectedSubjectsSchoolRank: null,
    subjectRanks: {
      语文: { class: 29, school: 662 },
      数学: { class: 6, school: 196 },
      英语: { class: 45, school: 850 },
      物理: { class: 11, school: 404 },
      化学: { class: null, school: null },
      生物: { class: null, school: null },
    },
  },
  {
    semester: "高一上学期",
    examName: "上学期", // 精简
    class: 9,
    subjects: {
      语文: 100,
      数学: 99,
      英语: 82,
      物理: 53,
      化学: 75,
      生物: 76,
    },
    originalTotalScore: 666,
    originalClassRank: "32",
    originalSchoolRank: "653",
    selectedSubjectsTotalScore: 100 + 99 + 82 + 53 + 75 + 76,
    selectedSubjectsClassRank: null,
    selectedSubjectsSchoolRank: 588,
    subjectRanks: {
      语文: { class: 40, school: 747 },
      数学: { class: 24, school: 515 },
      英语: { class: 46, school: 825 },
      物理: { class: 27, school: 550 },
      化学: { class: 17, school: 363 },
      生物: { class: 3, school: 205 },
    },
  },
  {
    semester: "高一下学期",
    examName: "3月", // 精简
    class: 9,
    subjects: {
      语文: 98,
      数学: 101,
      英语: 81,
      物理: 67,
      化学: undefined,
      生物: undefined,
    },
    originalTotalScore: 400,
    originalClassRank: "37",
    originalSchoolRank: "671",
    selectedSubjectsTotalScore: 98 + 101 + 81 + 67,
    selectedSubjectsClassRank: null,
    selectedSubjectsSchoolRank: null,
    subjectRanks: {
      语文: { class: 42, school: 798 },
      数学: { class: 20, school: 372 },
      英语: { class: 44, school: 801 },
      物理: { class: 7, school: 337 },
      化学: { class: null, school: null },
      生物: { class: null, school: null },
    },
  },
  {
    semester: "高一下学期",
    examName: "下学期", // 精简
    class: 9,
    subjects: {
      语文: 93,
      数学: 112,
      英语: 95.5,
      物理: 61,
      化学: 71,
      生物: 85,
    },
    originalTotalScore: 691.5,
    originalClassRank: "18",
    originalSchoolRank: "500",
    selectedSubjectsTotalScore: 93 + 112 + 95.5 + 61 + 71 + 85,
    selectedSubjectsClassRank: null,
    selectedSubjectsSchoolRank: 414,
    subjectRanks: {
      语文: { class: 35, school: 735 },
      数学: { class: 5, school: 227 },
      英语: { class: 39, school: 777 },
      物理: { class: 10, school: 284 },
      化学: { class: 19, school: 389 },
      生物: { class: 3, school: 73 },
    },
  },
]
